[package]
name = "lok_r4"
version = "0.1.0"
authors = ["TheOnlyMrCat <signupforforums5@gmail.com>"]
edition = "2018"

[dependencies]
inkwell = { version = "0.1.0-llvm10sample", features = ["llvm10-0"] }
lalrpop-util = "0.19.5"
